server:
  port: 9082

spring:
  cloud:
    nacos:
      discovery:
        server-addr: 26.99.234.0:8848
        metadata:
          my-key: my-meta-value
        service: student
        username: nacos
        password: nacos
        port: 9082
        weight: 1
        ephemeral: true